name: learn-github-actions
run-name: Testing CRANE on self-hosted runner
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - name: Install crane
        shell: bash
        run: |
          set -euo pipefail

          # Pin crane version and checksums
          CRANE_VERSION="v0.21.3"

          # Detect arch
          arch=$(uname -m)
          if [[ "$arch" =~ (aarch64|arm64) ]]; then
            arch="arm64"
            echo "${arch}"
            EXPECTED_CHECKSUM="dabcf2aee76ca72da63b5da5137c910a6852ccff13e35628e8f0a9dd8b73f4f3"
          else
            arch="x86_64"
            echo "${arch}"
            EXPECTED_CHECKSUM="46dbf12d943efa5673ab654186c5d7c1503580544de0df9325537083436fe5d0"
          fi

          echo "Installing crane ${CRANE_VERSION} for Linux ${arch}"

          # Download crane from official GitHub releases
          crane_tar="go-containerregistry_Linux_${arch}.tar.gz"
          crane_url="https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/${crane_tar}"
          pwd
          echo "Curling..."
          curl -fsSL --retry 5 --retry-delay 1 --retry-all-errors -o "${crane_tar}" "${crane_url}"
          # Verify SHA256 checksum
          echo "Validating sha..."
          echo "${EXPECTED_CHECKSUM}  ${crane_tar}" | sha256sum --check --strict -
          echo "===== Home folder location ===="
          echo "${HOME}"
          echo "==============================="
          echo "===== GITHUB_PATH ====="
          echo "${GITHUB_PATH}"
          echo "======================="
          # Extract directly to destination and add to PATH
          mkdir -p "${HOME}/.local/bin"
          tar -xzf "${crane_tar}" -C "${HOME}/.local/bin" crane

          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"       
          echo "===== GITHUB_PATH ====="
          echo "${GITHUB_PATH}"
          echo "======================="
          # Verify
          echo "===== CRANE Version ====="
          crane version


